### ISSUE TITLE
image with reference nobodyiam/apollo-quick-start was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

### ISSUE THREAD

**Issue by dachengxu** [apolloconfig/apollo-quick-start#97]
Apple M1 docker 方式启动失败

`
▶ docker-compose -f docker-compose-arm64.yml up

[+] Running 0/0

 ⠋ Container apollo-quick-start  Creating      

Error response from daemon: image with reference nobodyiam/apollo-quick-start was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

`

**Comment by nobodyiam** [comment]
The [docker image](https://hub.docker.com/r/nobodyiam/apollo-quick-start/tags) has been updated with both amd64 and arm64 support.
You may update your local cache or specify the tag to `2.1.0` directly.

```yaml
services:
  apollo-quick-start:
    platform: linux/arm64
    image: nobodyiam/apollo-quick-start:2.1.0
    container_name: apollo-quick-start
```

![image](https://user-images.githubusercontent.com/837658/219517664-1862bef0-5db5-4fda-b396-0230d670f5b2.png)
